---
title: "Presentaciones"
knitr:
  opts_chunk: 
    echo: false
    message: false
    warning: false
---

```{r}
#| echo: false
program <- readr::read_rds("program_complete.rds")

# charlas that the author did not fill the form 
# program$charlas |> 
#   dplyr::filter(is.na(author)) |> 
#   dplyr::pull(id) |> 
#   sort() |> 
#   cat(sep = ", ")

```

## Charlas / Talks / Palestras

```{r}
program$charlas |> 
  dplyr::arrange(tema) |> 
  dplyr::select(-id, -dia, -sesion, -lugar, -hora_inicio) |> 
  dplyr::relocate(author, .after = title) |> 
  reactable::reactable(sortable = TRUE,searchable = TRUE, filterable = TRUE,
    columns = list(
    title = reactable::colDef(name = "Título", minWidth = 100),
    author = reactable::colDef(name = "Authors", html = TRUE),
    body = reactable::colDef(name = "Descripción", html = TRUE, minWidth = 200),
    tags = reactable::colDef(name = "Palavras clave"),
    tema = reactable::colDef(name = "Tema")
  )
      
  )
```

## Posters

```{r}
program$posters |> 
  dplyr::arrange(id) |> 
  dplyr::select(-id) |> 
  reactable::reactable(sortable = TRUE,searchable = TRUE, filterable = TRUE,
    columns = list(
    title = reactable::colDef(name = "Título", minWidth = 100),
    author = reactable::colDef(name = "Authors", html = TRUE),
    body = reactable::colDef(name = "Descripción", html = TRUE, minWidth = 200),
    tags = reactable::colDef(name = "Palavras clave")
  )
      
  )
```


<!-- font awesome -->

```{=html}
<script src="https://kit.fontawesome.com/1f72d6921a.js" crossorigin="anonymous"></script>
```
<!-- font awesome -->