---
title: "Descubra Montevideo"
subtitle: "Guia de recursos turísticos do Latin-R 2023"
knitr:
  opts_chunk:
    echo: false
    message: false
    warning: false
---

Boas vindas a Montevideo, a vibrante capital do Uruguai e cidade anfitriã da Latin-R 2023. Este guia é para você, seja um participante da conferência querendo aproveitar ao máximo o seu tempo aqui, ou uma pessoa que já mora aqui e deseja redescobrir sua cidade junto com as pessoas convidadas internacionais. Compilamos uma lista de lugares essenciais para visitar e coisas para fazer em várias categorias: de restaurantes e entretenimento a pontos turísticos culturais e acomodações. Considere isto como seu recurso para encontrar links úteis e atividades que enriquecerão sua experiência na Latin-R 2023 em Montevideo. Vamos mergulhar no mundo de oportunidades que espera por você.

Você também pode encontrar mais informações em: <https://www.descubrimontevideo.uy/>

## Transporte em Montevideo

### A pé

Caminhar dentro de Montevideo é seguro e altamente recomendado para percursos curtos. Perto da FCEA, você encontrará o famoso e belo calçadão, onde pode se deslocar de Palermo até Cidade Velha, Centro ou Pocitos a pé!

### Bicicleta

Você também pode se locomover de bicicleta, pode encontrar as ciclovias dentro de Montevideo [aqui](https://montevideo.gub.uy/mapa-montevideo-en-bici).

#### Locais para alugar bicicletas

- [Orange Bike](https://orangebike.com.uy/)
- [Bike Tours Uruguay](https://biketoursuruguay.com/)
- [Mejor Uruguay](https://www.mejoruruguay.com/bicis1.php)

### Transporte público dentro de Montevideo (Ônibus)

Montevideo tem uma ampla rede de serviços de transporte em cada canto, o bilhete comum custa 52 pesos uruguaios (cerca de R$ 7,00) em dinheiro ou você também pode obter o cartão STM com seu passaporte e carregá-lo em diferentes locais distribuídos por toda a cidade, pagando assim um bilhete eletrônico de 42 pesos uruguaios (cerca de R$ 6,00).

- [Informação sobre STM aqui](https://montevideo.gub.uy/areas-tematicas/sistema-de-transporte-metropolitano/tarjetas-stm/tarjeta-comun)
- [Locais de atendimento STM](https://montevideo.gub.uy/locales-stm)


### Serviços de táxi:

- [Taxi de Montevideo](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjR67GdnuCBAxWrrpUCHd4xBZUQFnoECBwQAQ&url=https%3A%2F%2Fwww.voyentaxi.uy%2F&usg=AOvVaw0kwjd0lwOdB5et59J920b4&opi=89978449)
- [Uber](https://www.uber.com/global/es/cities/montevideo/)
- [Cabify](https://cabify.com/en)

As três opções podem ser pagas com cartão de débito e crédito, tanto em cada aplicativo quanto no veículo.

## Final de Semana no Bairro

- **[La Tira Parrillita de Palermo](https://goo.gl/maps/VBEWR1FpD4pzrB29A)**: Uma visita obrigatória para seus desejos de churrasco.
- **Su Bar**: Para o almoço durante a semana, considere [Su Bar](https://maps.app.goo.gl/fvFrDkHRinQNj4iW9).
- **Bar el FunFun**: Aproveite a música e as bebidas em [Baar el FunFun](https://maps.app.goo.gl/2ZPDQPhSpannDFVp9).

### Sabores locais

- **El Tacho**: Aproveite uma boa pizza em [Bar Tasende](https://maps.app.goo.gl/j4LVKLUYB1fn6x9RA).
- **Chivitos**: Desfrute do melhor chivito em um lugar diferente. [Localização](https://maps.app.goo.gl/rjiPCefxeJeAv3kZ8)

### Mercado del Puerto e Arredores

- **Mercado del Puerto**: Um mercado turístico, mas divertido.
- **Museo del Carnaval**: Conheça as tradições locais do Carnaval uruguaio.
- **Opções gastronômicas locais**: Visite [este lugar](https://maps.app.goo.gl/8xYxGRUkGd84i4VAA) para conhecer a comida local.
- **Boa comida**: Se o orçamento não é um problema, visite [este famoso lugar](https://maps.app.goo.gl/WNTR8R5hQKSW6aMk8).

---

## Restaurantes

- **Arcadia**: Desfrute da experiência gastronômica do [Restaurante Arcadia](https://www.radissonvictoriaplaza.com.uy/categoria/Restaurante-Arcadia-9).
- **La Casa Violeta**: Visite sua [página do Facebook](https://www.facebook.com/lacasavioleta/?locale=es_LA) para mais detalhes.
- **La Perdiz**: Você encontrará mais informações no [site de La Perdiz](https://laperdiz.com.uy/).

### Menções especiais

- **Plaza de Chueca**: Cozinha espanhola, super recomendado experimentar as tortillas e croquetes! [Está localizado em Maldonado 2051, 11200 Montevideo.](https://maps.app.goo.gl/yjBPrwduf1e7jSEq6) 
- **Mercado de Williman**: Conhecido pelas Mil Milas.
- **Mais opções**: Visite [esta localização](https://maps.app.goo.gl/ogr56T14YhrWTxSB6) para outra experiência culinária.

---

## Atrações de Futebol

- **Estadio Centenario**: Inclui um Museu do Futebol.
- **Parque Central**: Oferece um museu no Salão de Cristal.
- **Chorolo al Paso**: Comida rápida disponível [neste lugar](https://maps.app.goo.gl/KKS2xkcWZgrr85u39).

---

## Visitas Artísticas

- **Torres García**: Mais informações no [site de Torres Garcia](https://www.torresgarcia.org.uy/).
- **MNAV**: Visite o histórico Museu de Artes Visuais. [Site do MNAV](https://mnav.gub.uy/) para mais informações.
- **MAM**: Visite o Mercado Agricola de Montevideo, onde atualmente você pode encontrar diferentes ofertas gastronômicas. [MAM](https://www.mam.com.uy/).
- **El Rincón del Tango**: Junte-se ao grupo no [Facebook](https://www.facebook.com/groups/ELRINCONDELTANGO.2014/).

---

## Hotéis

- [**Dazzler by Wyndham Montevideo**](https://www.booking.com/Share-OB9n0Q).
- [**Ibis Montevideo Rambla**](https://www.booking.com/Share-56zkav).

---

Esperamos que este guia ajude você a planejar sua estadia em Montevideo para o Latin-R 2023. Aproveite a cidade, conheça novos lugares e pessoas e aproveite ao máximo a experiência da conferência!