---
title: "Discover Montevideo"
subtitle: "Latin-R 2023 Guide to Touristic Resources"
knitr:
  opts_chunk:
    echo: false
    message: false
    warning: false
---

Welcome to Montevideo, the vibrant capital city of Uruguay and the host city for Latin-R 2023! Whether you're a conference participant looking to make the most of your time here or a local keen to rediscover your city alongside our international guests, this guide is for you. We've curated a list of essential places to visit and things to do in various categories: from restaurants and entertainment to cultural landmarks and accommodations. Think of this as your go-to resource for useful links and activities that will enrich your Latin-R 2023 experience in Montevideo. Let's dive into the world of opportunities that await you.

You can also find more in: <https://www.descubrimontevideo.uy/>

## Transportation in Montevideo

### Walking

Walking within Montevideo is safe and highly recommended for short distances. Near FCEA, you'll find the famous and beautiful boardwalk, where you can walk from Palermo to Ciudad Vieja, Centro, or Pocitos!

### Bicycle

You can also get around by bicycle, you can find bike lanes within Montevideo [here](https://montevideo.gub.uy/mapa-montevideo-en-bici).

#### Places to rent bicycles

- [Orange Bike](https://orangebike.com.uy/)
- [Bike Tours Uruguay](https://biketoursuruguay.com/)
- [Mejor Uruguay](https://www.mejoruruguay.com/bicis1.php)

### Public Transportation within Montevideo (Bus)

Montevideo has an extensive network of transport services in every corner, the common ticket costs UY `$`52 (1.33 USD) in cash or you can also get the STM card with your passport and preload it at different locations distributed throughout the city, thus paying an electronic ticket of UY `$`42 (1.10 USD).

- [Information about STM here](https://montevideo.gub.uy/areas-tematicas/sistema-de-transporte-metropolitano/tarjetas-stm/tarjeta-comun)
- [STM Customer Service Locations](https://montevideo.gub.uy/locales-stm)

### Taxi Services:

- [Taxi de Montevideo](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjR67GdnuCBAxWrrpUCHd4xBZUQFnoECBwQAQ&url=https%3A%2F%2Fwww.voyentaxi.uy%2F&usg=AOvVaw0kwjd0lwOdB5et59J920b4&opi=89978449)
- [Uber](https://www.uber.com/global/es/cities/montevideo/)
- [Cabify](https://cabify.com/en)

All three options can be paid by debit and credit card, in each application as well as in the vehicle.


## Weekend in the Neighborhood

- **[La Tira Parrillita de Palermo](https://goo.gl/maps/VBEWR1FpD4pzrB29A)**: A must-visit for your barbecue cravings.
- **Su Bar**: For weekday lunch, consider [Su Bar](https://maps.app.goo.gl/fvFrDkHRinQNj4iW9).
- **Baar el FunFun**: Enjoy the music and drinks at [Baar el FunFun](https://maps.app.goo.gl/2ZPDQPhSpannDFVp9).

### Local Flavors

- **El Tacho**: For those brave enough, get the local experience at [El Tacho](https://maps.app.goo.gl/j4LVKLUYB1fn6x9RA).
- **Fergus chivitos**: Enjoy the best chivito at a rather underground setting. [Location](https://maps.app.goo.gl/rjiPCefxeJeAv3kZ8)

### Mercado del Puerto and Surroundings
- **Mercado del Puerto**: A touristy but fun market. 
- **Museo del Carnaval**: Learn about the local Carnival traditions.
- **El perro que fuma**: Check [this spot](https://maps.app.goo.gl/8xYxGRUkGd84i4VAA) for local food.
- **El Palenque**: If budget isn't a constraint, check out [this famous place](https://maps.app.goo.gl/WNTR8R5hQKSW6aMk8).

---

## Restaurants

- **Arcadia**: Enjoy the gastronomic experience at [Arcadia Restaurant](https://www.radissonvictoriaplaza.com.uy/categoria/Restaurante-Arcadia-9).
- **La Casa Violeta**: Visit their [Facebook page](https://www.facebook.com/lacasavioleta/?locale=es_LA) for more details.
- **La Perdiz**: You'll find more information on [La Perdiz's website](https://laperdiz.com.uy/).

### Special Mentions
- **Plaza de Chueca**: Spanish cuisine, highly recommend the tortillas and croquettes! [It's located at Maldonado 2051, 11200 Montevideo.](https://maps.app.goo.gl/yjBPrwduf1e7jSEq6)
- **Williman Market**: Known for the Mil Milas.
- **More options**: Visit [this location](https://maps.app.goo.gl/ogr56T14YhrWTxSB6) for another culinary experience.

---

## Football Attractions

- **Estadio Centenario**: Includes a Football Museum.
- **Parque Central**: Offers a museum in the Salón de Cristal.
- **Chorolo al Paso**: Quick bites available at [this location](https://maps.app.goo.gl/KKS2xkcWZgrr85u39).

---

## Artistic Visits

- **Torres García**: More information at [Torres Garcia website](https://www.torresgarcia.org.uy/).


- **MNAV**: Visit the historic Museum of Visual Arts. [MNAV's website](https://mnav.gub.uy/) for more information.

- **MAM**: Visit the Agricultural Market of Montevideo, where you can currently find different gastronomic offers [MAM](https://www.mam.com.uy/).

- **El Rincón del Tango**: Join the group on [Facebook](https://www.facebook.com/groups/ELRINCONDELTANGO.2014/).
- **Castillo Pitamiglio**: Visitors will be able to walk through and discover a labyrinth of infinite rooms and spaces, towers and a garden full of symbols and secrets. The center has exhibition spaces, an art gallery, a workshop area and a themed store. [Website](https://universopittamiglio.com/mvd.php)
---

## Hotels

- [**Dazzler by Wyndham Montevideo**](https://www.booking.com/Share-OB9n0Q).
- [**Ibis Montevideo Rambla**](https://www.booking.com/Share-56zkav).

---

We hope this guide enhances your Latin-R 2023 experience and helps you explore the various facets of Montevideo. Have a memorable time!

